apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: lak919/gateway-svc
        imagePullPolicy: Never
        env:
          - name: ClientApp
            value: https://app.nexauct.com
          - name: IdentityServiceUrl
            value: https://id.zehu.tech
            
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 80