apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: lak919/web-app
        imagePullPolicy: Always
        env:
          - name: API_URL
            value: http://gateway-svc-clusterip/
          - name: ID_URL
            value: https://id.zehu.tech
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: authSecret
          - name: NEXTAUTH_URL
            value: https://app.nexauct.com
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-clusterip
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
  - port: 3000
    targetPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: web-app-lb
# spec:
#   type: LoadBalancer
#   selector:
#     app: web-app
#   ports:
#   - port: 3000
#     targetPort: 3000
